"""Initial DB

Revision ID: 134856c6eb2b
Revises: 
Create Date: 2024-04-20 10:43:55.603503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134856c6eb2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
